services:
  nginx:
    image: nginx:1.30-alpine@sha256:dc5069ad14f19660b141b21236140b91656bf89bbc3e2417c70ae650cd66104c
    ports:
      - "8087:80"
    volumes:
      - ../../nginx/web27_nginx_static_reverse_proxy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../../frontend/static/studyweb/systems/web27_nginx_static_reverse_proxy/web:/usr/share/nginx/html:ro
    depends_on:
      - api

  api:
    build: ../../../backend/src/studyweb/systems/web27_nginx_static_reverse_proxy/api
    environment:
      PORT: 3000

